### ISSUE TITLE
When Ivona authentication fails, node fails silently and creates an mp3 with error message

### ISSUE THREAD

**Issue by oskarhagberg** [technocreatives/node-red-contrib-ivona-tts#2]
This is probably due to https://github.com/tmanderson/ivona-node not reporting this as an error.
1. Will try to create pull request for ivona-node. Or...
2. Create fork and a new NPM module to depend on. Or... 
3. Embed the Ivona implementation in this repository.

**Comment by Rawa** [comment]
Fixed GH-6
